dist: bionic

language: python

python:
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libsndfile1

install:
  - pip install tox-travis

script:
  - tox
