dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "pypy3"
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
script:
  # formatting
  - black --check vallenae/
  # linter
  - pylint vallenae/
  - flake8 vallenae/
  # tests
  - pytest