dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libsndfile1
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
script:
  # formatting
  - black --check vallenae/
  # linter
  - pylint vallenae/
  - flake8 vallenae/
  # type checks
  - mypy vallenae/
  # tests
  - pytest